const express=require("express");
const router=express.Router();
const {signUp,login,logoutUser,sendVerifyOtp,verifyEmail,resetotp,resetPswd,isAuthenticated}=require("../controllers/Auth");
const {auth}=require("../middlewares/auth");
router.post("/signUp",signUp);
router.post("/login",login);
router.post("/logout",logoutUser);
router.post("/sendOtp",auth,sendVerifyOtp);
router.get("/isAuth",auth,isAuthenticated);
router.post("/verifyEmail",auth,verifyEmail);
router.post("/resetotp",resetotp);
router.post("/resetpswd",resetPswd);
module.exports=router;