const mongoose=require("mongoose");
const userSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true
    },
    verifyotp:{
        type:String,default:""
    },
    verifyotpexpiry:{
        type:Number,default:0
    },
    isAccountVerified:{
        type:Boolean,default:false
    },
    resetotp:{
        type:String,default:""
    },
    resetotpexpiry:{
        type:Number,default:0
    }
})
module.exports=mongoose.model("User",userSchema);